### ISSUE TITLE
API ERROR when trying to save/edit a published glossary item?

### ISSUE THREAD

**Issue by pastarice** [xivresources/glossary.xivresources.com#9]
![chrome_UmxDcbPx1L](https://user-images.githubusercontent.com/54649371/129978763-752ad6ce-c3c3-4b92-bf34-581b19e255a6.png)

This issue comes up no matter what I try to do besides normal browsing :( please help I'm technologically illiterate

**Comment by nonowazu** [comment]
Looks like when I migrated this to an organization I forgot to grant the oauth app access to the org. I followed the instructions [here](https://github.com/netlify/netlify-cms/issues/1816#issuecomment-445599821) and I believe I fixed it.

Give it a try and let me know if it works for you?

**Comment by pastarice** [comment]
It worked :yay:
